// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWtA1JqRpFPIH8pHF-XAd738L0jnKkIQU',
    appId: '1:875512519846:web:0b0685b1feee625446e867',
    messagingSenderId: '875512519846',
    projectId: 'webrtc-1589d',
    authDomain: 'webrtc-1589d.firebaseapp.com',
    storageBucket: 'webrtc-1589d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFxgSQV58XB8YKqRajKbde1BjUtwgMKjI',
    appId: '1:875512519846:android:dae2bae464bfba8b46e867',
    messagingSenderId: '875512519846',
    projectId: 'webrtc-1589d',
    storageBucket: 'webrtc-1589d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAniaasgog3lSAVmp_0diIqKJayv7_7txM',
    appId: '1:875512519846:ios:b94346f1e2c17c5d46e867',
    messagingSenderId: '875512519846',
    projectId: 'webrtc-1589d',
    storageBucket: 'webrtc-1589d.appspot.com',
    iosBundleId: 'dev.flutterexplained.webrtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAniaasgog3lSAVmp_0diIqKJayv7_7txM',
    appId: '1:875512519846:ios:b7e68337e411e47146e867',
    messagingSenderId: '875512519846',
    projectId: 'webrtc-1589d',
    storageBucket: 'webrtc-1589d.appspot.com',
    iosBundleId: 'dev.flutterexplained.webrtcTutorial',
  );
}
